#!/usr/bin/env zsh
#
# Aliases
#

#
# Shell utils
#

alias ...='../..'
alias ....='../../..'
alias .....='../../../..'

alias l='ls -lG'
alias lh='l -ah'
alias ll='l -A'
alias lll='l -a'
#alias lsd='l -d'
alias lsd='ls -ld -- */' # https://securitronlinux.com/it/how-to-list-only-directories-with-the-ls-command-on-mac-osx/
alias lsize='ls -lx1hs'
alias lss='l -sS'
alias rm='nocorrect rm'
alias ls="ls --color=always"
alias c='noglob perl -le "print eval qq(@ARGV)"' # Try e.g. 'c 1+2'


#
# Manual pages
#
man () {
    # Colourful man pages
    LESS_TERMCAP_md=$'\e[01;31m' \
    LESS_TERMCAP_me=$'\e[0m' \
    LESS_TERMCAP_us=$'\e[01;32m' \
    LESS_TERMCAP_ue=$'\e[0m' \
    LESS_TERMCAP_so=$'\e[45;93m' \
    LESS_TERMCAP_se=$'\e[0m' \
    command man "$@"
}
alias öö=man

alias ltail='less -Ri +F'
alias mmv='noglob zmv -W' # Example: mmv *.conf.orig orig/*.conf
alias paths='echo $PATH | perl -pe "s/:/\n/g"'
alias stdout='$@ 2>&1'  # Combine stderr to stdout
alias xargs0='tr "\n" "\0" | xargs -0'

#
# Finding things
#

# Locate commands on your path
alias cmd='find $(paths) -name "$@" 2>/dev/null'

# Processes
alias pss='ps aux | grep -v grep | grep --color -i $@'

# Search is like ag/ack:
alias search='grep -r --exclude-dir=.git --exclude-dir=_darcs --exclude-dir=.bzr --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=vendor $1'

# Find largest/smallest files in a directory
alias biggest_files='find . -type f -ls | awk '{print $7 " " $11}' | sort -nr | head'
alias smallest_files='find . -type f -ls | awk '{print $7 " " $11}' | sort -n | head'
lsz () {
    local dir="$1"; shift
    find $dir -type f | xargs ls -lah1s | sort -n $@
}

#
# Logs
#

# Example: tail log files written in the last month, whose name match the grep argument.
# logs -atime -30d | grep -E '(sys)' | xargs tail -f
logs () {
    find {/usr/local,/opt/local,/sw,}/var/log{/apache2,/nginx,} -type f -name '*[._]log' -and $@ -print 2>/dev/null
}

#
# Text utils
#

alias tabify="replace ' +' '\t'"
alias untabify="replace '\t' '    '"
alias quotelines="replace '^(.*)\n' '\"\1\"\n'"

doublelines () { perl -pe 's/\n/\n\n/' }
removehyphens () { perl -pe 's/-$//' }
replace () { perl -pe "s/$(echo $1)/$(echo $2)/g" }
striplines () { ruby -ne 'puts $_.strip' }
trim () { awk '{$1=$1};1' } # Works only when piped into

null_separate_sections () {
    # -0777 reads whole input at once
    ruby -0777 -pe 'gsub(/\n\n/, "\0")' | perl -pe 's/\n/ /'
}

grep_sections () {
    # Grep input by sections (separated by two newlines)
    grep -B8 -A24 $* | striplines | removehyphens | null_separate_sections | \
	xargs -0 -n1 echo | \
	grep $*
}

#
# Utils
#

# Print and test CLI argument expansion
argv () { python -c 'import sys; print(sys.argv[1:])' "$@" }

# Grep manpages by sections
about () {
    local cmd=$1; shift
    man $cmd | grep_sections $* | doublelines
}

#
# Services
#
alias weather='curl http://wttr.in'
alias moon='curl http://wttr.in/Moon'
cheat () { curl "cheat.sh/$1" }

#
# Git
#
require "${ZDOTDIR:-$HOME}"/zsh/garden/aliases_git

#
# Programming
#

alias todo='search -E "((//|#|--|;;?)\s+(TODO|REMOVEME|FIXME))"'
alias svn-commits-for-merge="cut -d'|' -f1 | sort -u | perl -pe 's/ *r([0-9a-f]+) *\n/\1,/g'"

# Python
alias pim='python manage.py'

# Databases
#

# PostgreSQL
#alias pg="sudo -u postgres pg_ctl $1 -D $PGDATA -l $PGDATA/pgsql.log"

#
# System specific aliases
#
if os_type 'Darwin'; then
    require "${ZDOTDIR:-$HOME}"/zsh/garden/aliases_osx
elif os_type 'Linux'; then
    require "${ZDOTDIR:-$HOME}"/zsh/garden/aliases_linux
elif os_type 'FreeBSD'; then
    require "${ZDOTDIR:-$HOME}"/zsh/garden/aliases_freebsd
fi


#
# Local aliases
#
require "${ZDOTDIR:-$HOME}"/.aliases.local
