#!/usr/bin/env zsh

quiet stopwatch
debug FUNCTIONS


# File search functions
function f() { find . -iname "*$1*" ${@:2} }
function r() { grep "$1" ${@:2} -R . }

# Create a folder and move into it in one command
function mkcd() { mkdir -p "$@" && cd "$_"; }


# Find all symlinks to file / directory
# https://unix.stackexchange.com/a/482995
# usage $1 = the target of symlinks
#       $2 = the directory to from where find (recursively)
#       USE ABSOLUTE PATHS!
function findsym() { print -rC1 "$2"/**/*(ND@e['[[ $REPLY:P = "$1" ]]']) }

function findsymdetail() { ls -ld "$2"/**/*(ND@e['[[ $REPLY:P = "$1" ]]']) }

# Work related functions
require "${ZDOTDIR:-$HOME}"/zsh/garden/functions_work

debug_loadtime FUNCTIONS
